### PR TITLE
Create AnewFile

### PR DESCRIPTION
**Pull request by TheFakePaulLeTang**
Cause we need it.

Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by paulletang** [comment]
This is pretty cool.
image

**Review by paulletang — APPROVED** [review]
Approving, but do a thing first.
- [x] A thing

**Comment by paulletang** [comment]
- [ ] Do this other thing

**Comment by TheFakePaulLeTang** [comment]
Help, I need an adult.

image

**Comment by TheFakePaulLeTang** [comment]
The tasks are all done, but I still need an adult!

image

**Comment by TheFakePaulLeTang** [comment]
Even when targeting a non-restricted branch, I can't merge this in!

image

**Comment by paulletang** [comment]
This feels sufficiently locked down to me.
We might want to rethink our use of tasks though, as it looks like you need an elevated permission to be able to check them.

**Pull request closed without merging**
